### ISSUE TITLE
为什么解析过的下载链接是baidupan.com的？

### ISSUE THREAD

**Issue by Huaweidev** [daimiaopeng/LanZou#1]
为什么解析过的下载链接是baidupan.com的？
[https://development5.baidupan.com/092612bb/2019/09/20/0a5aa393696022da7731b7fd1deea7fc.zip?st=N1xgzITVylOCJJmI81dr5w&e=1569473689&b=UTYBN1BjAz9WNldiCm4BM1RgAD1XZAViAWQKNlI3VTMFYQoyAGZSZlU0AjFRZwAzBjYNaQdnUWBUNQk8VzFSYlE0AWVQZAM3VmZXMwpoAWBULwAmVz8Fcw_c_c&fi=12284946&up=](url)

**Comment by daimiaopeng** [comment]
这个不是百度的域名，你可以去查whois信息，域名在蓝奏云公司下，至于这名字我觉得有点意思。



---原始邮件---
发件人: "Jeff Li"<notifications@github.com&gt;
发送时间: 2019年9月26日(星期四) 中午12:23
收件人: "daimiaopeng/lanzou"<lanzou@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [daimiaopeng/lanzou] 为什么解析过的下载链接是baidupan.com的？ (#1)



为什么解析过的下载链接是baidupan.com的？
 https://development5.baidupan.com/092612bb/2019/09/20/0a5aa393696022da7731b7fd1deea7fc.zip?st=N1xgzITVylOCJJmI81dr5w&amp;e=1569473689&amp;b=UTYBN1BjAz9WNldiCm4BM1RgAD1XZAViAWQKNlI3VTMFYQoyAGZSZlU0AjFRZwAzBjYNaQdnUWBUNQk8VzFSYlE0AWVQZAM3VmZXMwpoAWBULwAmVz8Fcw_c_c&amp;fi=12284946&amp;up=

**Comment by colemanlee** [comment]
Whois只能查到alibaba的信息，怎么查到蓝奏的信息呢？能否您直接转出来baidupan.com的直链？万一您的服务器故障怎么办？

**Comment by Huaweidev** [comment]
> 这个不是百度的域名，你可以去查whois信息，域名在蓝奏云公司下，至于这名字我觉得有点意思。
> […](#)
> ---原始邮件--- 发件人: "Jeff Li"<notifications@github.com&gt; 发送时间: 2019年9月26日(星期四) 中午12:23 收件人: "daimiaopeng/lanzou"<lanzou@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [daimiaopeng/lanzou] 为什么解析过的下载链接是baidupan.com的？ (#1) 为什么解析过的下载链接是baidupan.com的？ https://development5.baidupan.com/092612bb/2019/09/20/0a5aa393696022da7731b7fd1deea7fc.zip?st=N1xgzITVylOCJJmI81dr5w&amp;e=1569473689&amp;b=UTYBN1BjAz9WNldiCm4BM1RgAD1XZAViAWQKNlI3VTMFYQoyAGZSZlU0AjFRZwAzBjYNaQdnUWBUNQk8VzFSYlE0AWVQZAM3VmZXMwpoAWBULwAmVz8Fcw_c_c&amp;fi=12284946&amp;up= — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Whois只能查到alibaba的信息，怎么查到蓝奏的信息呢？能否您直接转出来baidupan.com的直链？万一您的服务器故障怎么办？

**Comment by daimiaopeng** [comment]
你可以查备案信息
还有我解析用的服务器是阿里的云函数






------------------ 原始邮件 ------------------
发件人: "Jeff Li"<notifications@github.com>; 
发送时间: 2019年9月26日(星期四) 中午12:57
收件人: "daimiaopeng/lanzou"<lanzou@noreply.github.com>; 
抄送: "初音喵喵喵"<844362911@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [daimiaopeng/lanzou] 为什么解析过的下载链接是baidupan.com的？ (#1)




Whois只能查到alibaba的信息，怎么查到蓝奏的信息呢？能否您直接转出来baidupan.com的直链？万一您的服务器故障怎么办？
